import numpy as np
from PIL import Image
from scipy import ndimage
S=0.42
KEY=0xF81F
def clean(a):
    a=a.copy()
    for _ in range(4):
        op=a[...,3]>0
        edge=op & ~ndimage.binary_erosion(op)
        bright=(a[...,:3].min(-1)>175)
        kill=edge&bright
        if not kill.any(): break
        a[kill,3]=0
    return a
def shrink(name):
    a=clean(np.array(Image.open(name+'.png').convert('RGBA')).astype(float))
    h,w=a.shape[:2]
    nw,nh=max(1,round(w*S)),max(1,round(h*S))
    al=a[...,3:4]/255.
    pm=a[...,:3]*al
    def rs(ch): return np.array(Image.fromarray(ch.astype(np.float32),'F').resize((nw,nh),Image.BOX))
    A=rs(al[...,0]); C=np.stack([rs(pm[...,i]) for i in range(3)],-1)
    C=C/np.maximum(A[...,None],1e-6)
    # darken semi-covered edge pixels slightly toward outline tone
    return np.clip(C,0,255).astype(np.uint8), (A>0.45), (nw/w, nh/h)
# joints measured in SOURCE pixels of the extracted crops
J={
 'torso':  {'pivot':(91,288),'neck':(91,34),'shL':(18,64),'shR':(164,64),
            'hipFL':(66,270),'hipFR':(116,270),'hipBL':(52,246),'hipBR':(130,246),'abd':(122,240)},
 'head':   {'pivot':(146,214),'eyeL':(89,142),'eyeR':(206,142),'mouth':(146,197)},
 'abdomen':{'pivot':(90,14)},
 'arm':    {'pivot':(112,24),'end':(82,136)},
 'scythe': {'pivot':(10,52),'tip':(146,160)},
 'thigh':  {'pivot':(100,16),'end':(20,104)},
 'shin':   {'pivot':(48,12),'end':(44,176)},
}
src={'torso':'torso','head':'head','abdomen':'abdomen','arm':'arm_upper_L','scythe':'scythe_A','thigh':'thigh0','shin':'shin2'}
def c565(r,g,b):
    v=((int(r)&0xF8)<<8)|((int(g)&0xFC)<<3)|(int(b)>>3)
    return 0xF81E if v==KEY else v
out=['#pragma once','// AUTO-GENERATED by tools/build_rig.py from the art in art/ — do not hand edit.',
     '// Transparent key = 0xF81F. Joints are in sprite pixel coords (float).','#include <stdint.h>',
     f'static const uint16_t RIG_KEY = 0x{KEY:04X};',
     'struct RigPart { const uint16_t *px; int16_t w, h; float pvx, pvy; };','']
prev=[]
for part,f in src.items():
    C,M,(sx,sy)=shrink(f); h,w=M.shape
    vals=[c565(*C[y,x]) if M[y,x] else KEY for y in range(h) for x in range(w)]
    out.append(f'static const uint16_t RIG_{part.upper()}_PX[{w*h}] = {{')
    for i in range(0,len(vals),16): out.append('  '+','.join(f'0x{v:04X}' for v in vals[i:i+16])+',')
    out.append('};')
    pv=J[part]['pivot']
    out.append(f'static const RigPart RIG_{part.upper()} = {{ RIG_{part.upper()}_PX, {w}, {h}, {pv[0]*sx:.2f}f, {pv[1]*sy:.2f}f }};')
    for jn,(x,y) in J[part].items():
        if jn=='pivot': continue
        out.append(f'static const float RIG_{part.upper()}_{jn.upper()}_X = {x*sx:.2f}f, RIG_{part.upper()}_{jn.upper()}_Y = {y*sy:.2f}f;')
    out.append('')
    Image.fromarray(np.dstack([C,M*255]).astype(np.uint8)).save('small_'+part+'.png')
    print(part,w,h)
open('mantis_rig.h','w').write('\n'.join(out)+'\n')
